### ISSUE TITLE
Can't invite someone who already have an account

### ISSUE THREAD

**Issue by tibo** [Linkastor/Linkastor#19] opened 2015-06-24 20:49 UTC
to reproduce -> create an new group and try invite someone who already have an account (but belong to another group)

**Comment by vdaubry** [comment] 2015-06-25 09:23
@tibo Cannot reproduce locally :
- Started with a fresh DB
- Create seed group (rake db:seed)
- Sign up and create a group (=> i'm a member of this group)
- Send an invite to me to join the seed group
- I accept the invite
- I'm a member of the 2 groups

Do you see how i could reproduce the problem ?

![screen shot 2015-06-25 at 11 22 50](https://cloud.githubusercontent.com/assets/498298/8351269/50891f9c-1b2c-11e5-865e-880edc8194ef.png)

**Comment by tibo** [comment] 2015-06-25 09:41
can reproduce it really easily in production
![screen shot 2015-06-25 at 11 41 01](https://cloud.githubusercontent.com/assets/309695/8351619/199a7ca8-1b2f-11e5-9751-102225a3ef67.png)

**Comment by vdaubry** [comment] 2015-06-25 13:17
Ok there is already a pending invitation for me to this group, that's why you couldn't invite me to this group

I'll close this issue and create some other ones :
- I didn't receive the invitation, is the invitation mail broken on Heroku ?
- There should be a better error message when the invitation already exists
- We should be able to see pending invitation on a group and be able to re-send them (feature)

> Invite id: 1, referrer_id: 1, email: "vdaubry@gmail.com", code: "1ff473d87d24c119c880", group_id: "1", accepted: false, created_at: "2015-06-03 12:00:25", updated_at: "2015-06-03 12:00:25">

**Closed as completed by vdaubry** 2015-06-25 13:17 UTC
